## What is Ifá?

The traditions, practices, and spritual system of the Yoruba people of West Africa. It a system of divination, ethics, cosmology, and a way of life. It is one the oldest spritual traditions in the world, predating many of the most popular religions and spritiual systems of the world. The Yoruba religion is the root of many of the African Traditional Religions (ATR) such as Santería, Candomblé, and Vodun. The divniation system is based on the Holy Odu which consists of 256 Odu (chapters). They are broken down into 16 major Odu and 246 minor Odu, with each containing many ẹsẹ (verses). The Holy Odu states that we all have a chosen destiny that we must fulfill. As Chief Solagbade Popoola says "If you seek the truth, come to Ifá."

## Who is Olódùmarè?
Olódùmarè is the creator and source of all that is in the universe.

## What are [Órìṣà/Orisha](orisha.qmd)?
Órìṣà are the divine spirits and forces of nature created by Olodumare which help to guide human consciousness and move us towards living in íwa-pȩ̀lȩ́ (good character).

## Traditions of Ifá

### Isese
Isese is the traditional spritual religon/traditions of the Yoruba people in southwestern Nigeria. It is the original of the three major paths of Ifá.

[Chief Solagbade Popoola discussing Isese](https://www.youtube.com/live/juc_kapaUFo?feature=share)

### Santería / Lucumí / Regla de Ocha

Santería is the afro-cuban tradition of Ifá. It was birthed through a syncretism process where the enslaved mostly Yoruba people blended the traditions of the Yoruba religion with Catholicism. The Spanish enforced Catholicism as the only religion one could practice legally. The Orisha were syncretized with Catholic saints.

### Candomblé

Candomblé is the Brazilian tradition of Ifá. It was birthed through a syncretism process where the enslaved mostly Yoruba people blended the traditions of the Yoruba religion with Catholicism. The Portuguese enforced Catholicism as the only religion one could practice legally. The Orisha were syncretized with Catholic saints.

## Initiations, Rituals, and Ceremonies (More to come)

### Íṣẹ́fá / Hand of Ifa / Mono de Orula

The Hand of Ifa is the first step in the process of initiation into Ifa. The initiaion is typically a three day long ritual. What you will recieve can vary depending on the lineage you are initiating or tradition you're initating into. At the very least you will recieve:

1. A divination where you will be given some information of your destiny and your specific eewo (taboos). A more full view of your destiny and path are given Itefá (the full initiation into Ifá / Priesthood). Your eewo(taboos) are specific to you and is to be taken seriously as they are the things you must avoid in order to be spritually healthy and be in íwa-pȩ̀lȩ́ (good character).

2. A bracelet(Idé Ifá) and/or Ilẹkẹ(beaded necklace) which will be either green and brown or green and yellow which. In order to prevent Iku(Death) from taking people before their time Orunmila make a pact with Iku that if someone was wearing these colors that they are not to be taken before their time. It is protection, a symbol of your initiation into Ifá and your pact with Orunmila.

3. You are given one or multiple consecrated shines that you need to nourish and care for.



