# Órìṣà (Orisha)

## Ori

Ori is your personal Órìṣà. It's the spiritual higher self, our intuition, and personal spritual guide. Ori is the keeper of our destiny and the one who guides us to our purpose on Aye(Earth). Every living being is born with an Ori. Blessing cannot occur without the permission of Ori. When in alignment with ourselfs and Ori, we are able to manifest our destiny. When were are not in alignment ourselves we can turn blessings away.

## Èṣù / Eshu / Ẹlẹ́gbára / Eleguá

Èṣù is the Órìṣà of crossroads, duality, beginnings, and endings, postive and negative. Èṣù holder of aṣe(power) and is the messenger between the Òrìṣà and humans. Èṣù is somewhat mischevious, by tempting, tharwting, and disrupting to test our character. If the tests are passed then everything is made right and blessing are given. Èṣù is the frist to be called upon in rituals or ceremonies and is the to be given a part of any offering and/or sacrifce before all Órìṣà, and even before Egun(ancestors). Èṣù is typically depicted using wood, clay or concreate and adnored with cowrie shells. Èṣù colors are black and red and is found in nature at crossroads and gateways.

[Video](https://youtu.be/821e5mtYjnY){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000605270889){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/358JWuO3I2exTmdUJMEiLE?si=ab60dc1aa58f45eb){target="_blank"}

## Orunmila / Orúnmìlà / Ifá

Orunmila is the prophet of Ifá. Orunmila developed and expounded upon the Ifá divination system. Orunmila is the one who communicates the will of Olodumare to the Òrìṣà and humans. He holds the secrets to the universe and the destiny of all beings.

[Video](https://youtu.be/hmTf2jp61D4){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000585258936){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/0pVSEpTEiJsGAT01Sw86GQ?si=38c46ce3867a4704){target="_blank"}

## Ọbàtálá / Obatala

Ọbàtálá means "Chief of the White Cloth". Ọbàtálá is the creator of the Earth, sky and humans. He is the Órìṣà of purity, peace, creation, wisdom, and the protector of people with disabilities. Ọbàtálá is considered the father of all Òrìṣà. As a human Ọbàtálá was founder and the King of Ile-Ife an ancient city now in the Osun state of Nigeria. Ọbàtálá colors are white and can be found in nature on mountains and large hills.

[Video](https://youtu.be/tyWrpK_lU5c){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000588918368){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/5xRMcwHigHjDn7u9LSERD0?si=43863eaf8d0a4f2c){target="_blank"}

## Olóòkun / Olokun

Olóòkun is the Órìṣà of the ocean and all of its mysteries. Olóòkun is the Órìṣà health, monatery wealth, and prosperity. They are often described as intersex and having masculine and feminime charactersitics. Olóòkun colors are blue and green and can be found in nature in the depths of the ocean.

[Video](https://youtu.be/W4uURtIGUGw){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000589779343){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/3dkLbi8QaAYJD3IGc6J22H?si=31e4fbd06a394511){target="_blank"}

## Yemọja / Yemaja

Yemọja is one of many Órìṣà of the river. In Santeria she is the Órìṣà of the ocean along with Olokun. Yemọja is the Órìṣà of motherhood, fertility, wealth, and the protector of children and is often considered as the mother of all Òrìṣà. Yemọja colors are blue and white and can be found in nature in rivers, streams and the ocean.

[Video](https://youtu.be/8qbWBWH_cJc){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000603827038){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/7nWzMosGi8TipLX6P16KR7?si=998a15c0b70543b4){target="_blank"}

## Ọṣun / Oshun
Ọṣun is possibly the most popular and reconizable Órìṣà, especially in the diaspora. Ọṣun is a river spirit, specifically of the Oshun river. She is the Órìṣà of love, beauty, fertility, and sensuality. Oshun colors are yellow and gold and can be found in nature in rivers and streams.
[Video](https://youtu.be/rwkxt7p5_JE){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000582083738){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/6csrZ0tcwsFftz6OZGid9S?si=b0a45c392c314e3e){target="_blank"}

## Ọbà / Oba / Obba

[Video](https://youtu.be/txJ1XSa9JEg){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000608098826){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/0hbFYI5nLVfyPj8Fm0RR3a?si=e26be9d92dd24bc0){target="_blank"}

## Ṣàngó / Shango

[Video](https://youtu.be/h2Da5zuUUos){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000584424404){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/6uGcqm8ubxGv4HQCDmT05a?si=b8cbba20aa834c91){target="_blank"}

## Ọya / Oya

[Video](https://youtu.be/kUPH41ZOCGA){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000598088059){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/0cMRZtPPOFKE080WpyBhRB?si=e266a2d8f8904826){target="_blank"}

## Ògún / Ogun

[Video](https://youtu.be/DvtNHdVw5Lk){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000595974801){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/0u95tNQOVn67oNG7Ojmgyu?si=9527655ed7334706){target="_blank"}

## Ọ̀ṣọ́ọ̀sì / Oshosi

[Video](https://youtu.be/UTfwjXY2fbU){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000594523916){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/3zHAojsLMD2y5x1sDV83GY?si=8dce72ce1c8840c7){target="_blank"}

## Erinlẹ / Erinle

[Video](https://youtu.be/2v3HxdCNZ28){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000614787230){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/4uSq3o93DLG3Rmr6jbk4v3?si=1f76423b8c6e424e){target="_blank"}

## Babalú-Aye / Babaluaye

[Video](https://youtu.be/YdpkQJRz5p0){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000610309879){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/2JcmcxaaYEqFb7LKqyk4qP?si=3e92690962444075){target="_blank"}

## Aganju

[Video](https://youtu.be/WQJg1OSd7TA){target="_blank"}

[Apple Podcast](https://podcasts.apple.com/us/podcast/our-roots-only-the-strongest-roots-see-the-light/id1645823074?i=1000601669922){target="_blank"}

[Spotify Podcast](https://open.spotify.com/episode/5HP31NSRcxFjrTo2ifkJjY?si=e539af40da594a7b){target="_blank"}